services:
  - name: misevents-server
    type: web
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false

  - name: misevents-client
    type: web
    runtime: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://misevents-server.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
